/* 後から内容を追加する場合は、ここで管理できます。未設定情報は空のままにします。 */
const SITE = {name:'［任意団体］総武鉄道', tagline:'こんにちは。', services:[{name:'RobloxでPlayする',href:'https://www.roblox.com/ja/home'},{name:'Robloxグループに参加する',href:'https://www.roblox.com/share/g/477136599'},{name:'Discord コミュニティーサーバーリンク',href:''}]};
const NAV_ITEMS = [['index.html','トップページ','home'],['news.html','お知らせ','news'],['routes.html','路線・駅情報','routes'],['about.html','団体について','about'],['regulations.html','社員規定','regulations'],['recruitment.html','リンク・社員募集','recruitment'],['contact.html','お問い合わせ','contact']];
const LINE_DATA = [{name:'快速線',english:'Rapid Line'},{name:'各停線',english:'Local Line'}];
function renderHeader(){const current=document.body.dataset.page;const links=NAV_ITEMS.map(([href,label,key])=>`<a href="${href}" class="${current===key?'is-current':''}">${label}</a>`).join('');document.querySelector('#site-header').innerHTML=`<header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="${SITE.name} トップページ"><img class="brand-logo" width="42" height="42" src="assets/logo/IMG_8780.png" alt="総武鉄道 SR"><span class="brand-text">${SITE.name}<small>RAILWAY COMMUNITY</small></span></a><button class="menu-toggle" type="button" aria-label="メニューを開く" aria-expanded="false"><i></i></button><nav class="global-nav" aria-label="メインナビゲーション">${links}</nav></div></header>`;const button=document.querySelector('.menu-toggle');button.addEventListener('click',()=>{const open=button.classList.toggle('is-open');document.querySelector('.global-nav').classList.toggle('is-open',open);button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');});}
function renderFooter(){const pages=NAV_ITEMS.map(([href,label])=>`<a href="${href}">${label}</a>`).join('');const services=SITE.services.map(({name,href})=>href?`<a href="${href}" target="_blank" rel="noopener noreferrer">${name}</a>`:`<span>${name}（リンク準備中）</span>`).join('');document.querySelector('#site-footer').innerHTML=`<footer class="site-footer"><div class="container footer-top"><div><a class="brand footer-brand" href="index.html"><img class="brand-logo" width="42" height="42" src="assets/logo/IMG_8780.png" alt="総武鉄道 SR"><span class="brand-text">${SITE.name}<small>RAILWAY COMMUNITY</small></span></a><p class="footer-description">Robloxを中心に活動する任意団体です。<br>本サイトに掲載されている鉄道・路線等はRoblox上で展開される架空のコンテンツです。</p></div><div class="footer-column"><h3>PAGES</h3><div class="footer-links">${pages}</div></div><div class="footer-column"><h3>SERVICES</h3><div class="footer-links footer-links--services">${services}</div></div></div><div class="container footer-bottom"><p class="footer-notice">${SITE.name}は、Robloxを中心に活動する任意団体です。実在する鉄道事業者・企業・団体等とは関係ありません。</p><span>© ${SITE.name}</span></div></footer>`;}
function bindInteractions(){document.querySelectorAll('[data-toast]').forEach(button=>button.addEventListener('click',()=>{const toast=document.createElement('div');toast.className='toast';toast.textContent=button.dataset.toast;document.body.append(toast);setTimeout(()=>toast.remove(),2600);}));const form=document.querySelector('[data-contact-form]');if(form)form.addEventListener('submit',event=>{const status=form.querySelector('[data-form-status]');if(!form.checkValidity()){event.preventDefault();status.textContent='未入力の項目を確認してください。';form.reportValidity();}});}
function initReveal(){const elements=document.querySelectorAll('.menu-grid a,.line-cards article,.info-grid article,.service-list>div,.placeholder-panel,.empty-state');if(!('IntersectionObserver' in window)){elements.forEach(element=>element.classList.add('is-visible'));return;}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.08});elements.forEach(element=>{element.classList.add('reveal');observer.observe(element);});}
function initRegulationAppendix(){const list=document.querySelector('[data-regulations]');if(!list)return;list.insertAdjacentHTML('beforeend','<section class="regulation-chapter"><h2>附則</h2><p>第7項　本規定による社員間の警告は、場合による社内討議にて決定する場合がある。</p><p>以上</p></section>');}
function removeRouteMap(){const routeMap=document.querySelector('.route-map');if(routeMap)routeMap.closest('.section')?.remove();}
document.addEventListener('DOMContentLoaded',()=>{renderHeader();renderFooter();bindInteractions();initReveal();initRegulationAppendix();removeRouteMap();document.body.classList.add('is-ready');});
